services:

    JulienIts\EmailsQueueBundle\Services\EmailService:
        autowire: true
        public: true

    JulienIts\EmailsQueueBundle\Services\EmailsQueueService:
        autowire: true
        public: true

    JulienIts\EmailsQueueBundle\Command\EmailsCommand:
        autowire: true
        public: true
        tags:
            - { name: 'console.command', command: 'jits:queue:process' }

    JulienIts\EmailsQueueBundle\Repository\EmailContextRepository:
        autowire: true
        tags: [ 'doctrine.repository_service' ]

    JulienIts\EmailsQueueBundle\Repository\EmailQueueRepository:
        autowire: true
        tags: [ 'doctrine.repository_service' ]

    JulienIts\EmailsQueueBundle\Repository\EmailSentRepository:
        autowire: true
        tags: [ 'doctrine.repository_service' ]